spring.application.name=forum-hub

spring.datasource.url=${DB_FORUMHUB}
spring.datasource.username=${DB_USER_MYSQL}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

spring.security.token.secret=${JWT_SECRET}
logging.level.org.springframework.security=DEBUG
